FROM python:3.10


# Install requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy everything in
COPY . /repository
WORKDIR /repository


# Run unit tests by default
CMD ["python3", "-m", "pytest", "tests/unit", "-s", "--cov", "src", "--cov-config", "tox.ini", "--cov-report", "html", "--cov-report", "term"]
