name: run-unit-integration-tests-and-check-style

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: build-linter-image
        run: docker build -f Dockerfile.linting -t app-tox-worker .

      - name: check-linting-tests
        run: docker run app-tox-worker tox

      - name: build-unit-test-image
        run: docker build --file Dockerfile.unit_tests --tag app_unit_tests .

      - name: run-unit-tests
        run: docker run --network=host --volume="$PWD/coverage/":/var/coverage/ app_unit_tests

      - name: build-integration-test-image
        run: docker build --file Dockerfile.integration_git --tag app_integration_tests .

      - name: run-integration-tests
        run: docker run app_integration_tests
